import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/theme/globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { getAntdTheme } from '@/theme/antd.theme';
import { SWRProvider } from '../../@next/context/SWRProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Boiler By Waqas.',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SWRProvider>
          <AntdRegistry>
            <ConfigProvider theme={getAntdTheme('light')}>
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </SWRProvider>
      </body>
    </html>
  );
}
